### ISSUE TITLE
Errors installing aihwkit

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#289]
Hello,

As part of a project I'm working on for my studies, we want to use the "Analog Hardware Acceleration Kit" you developed. Were having trouble installing the kit properly, despite following the Advanced Installation guide here: https://aihwkit.readthedocs.io/en/latest/advanced_install.html and we hoped to consult with you.

We work on Linux Ubuntu 20.04 using vscode. We receive two types of errors:

1. aihwkit.excptions.CudaError: aihwkit has not been compiled with CUDA support
2. ModuleNotFoundError: No module named 'aihwkit.inference'
 
Regarding the first error - first, we tried installing aihwkit using pip (the default installation) and we got this problem. we thought that the source doesn't compile automatically with CUDA and we proceeded to the advanced installation. On our second attempt, we tried installing as specified by the Advanced Installation Guide, but we're still getting this error. Do you have any idea what can cause it? (We're pretty sure CUDA toolkit & OpenBLAS are installed on the computer)

About the second error - some examples from the git: https://github.com/IBM/aihwkit/tree/master/examples run (e.g. #1 and #2), but some fail (e.g. #3).. We see that most aihwkit modules were installed properly, perhaps you have any idea what can cause this problem with this specific module?

Do you have any suggestion what can we do next in order to install this kit?

Thank you very much for your time and attention.

**Comment by ElinorG11** [comment]
I found it under `aihwkit_env/lib/python3.8/site-packages`, I will try adding both `~/aihwkit_env/lib/python3.8/site-packages` and `~/aihwkit/src` to `PYTHONPATH`. thank you

**Comment by maljoras** [comment]
I see, you have chosen the virtual environment install option, I did not know that. Yes, indeed then it is in the `virtual_env` folder. You should only need to add that `site-package` folder to the `PYTHONPATH`.

**Comment by ElinorG11** [comment]
Thank you! it worked. the steps I followed in case anyone is having trouble with it as I did:
**after activating the virtual environment**
1. clone the kit using `(aihwkit_env) ~$ git clone https://github.com/IBM/aihwkit.git` into the home directory `/home/usr`
2. go to the folder where the src is by `(aihwkit_env) ~$ cd /home/usr/aihwkit`
3. compile the kit `(aihwkit_env) ~/aihwkit$ python setup.py build_ext --inplace -DUSE_CUDA=ON`
4. add the __full path__ to the folder `src/aihwkit` e.g. `(aihwkit_env) ~$ export PYTHONPATH=/home/usr/aihwkit/src/aihwkit`
